version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: local
    volumes:
      - ./migrations/bootstrap:/docker-entrypoint-initdb.d
